#ifndef __KL2EDK_AUTOGEN_aliases__
#define __KL2EDK_AUTOGEN_aliases__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'aliases.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version {{ version_full }}
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != {{ version_maj }} || FABRIC_EDK_VERSION_MIN != {{ version_min }}
# error "This file needs to be rebuilt for the current EDK version!"
#endif

namespace Fabric { namespace EDK { namespace KL {

{% for name in manager.aliases %}
{% set alias = manager.aliases[name] %}
// KL alias '{{ alias.newname }}'
// Defined at {{ alias.location }}
typedef {{ alias.oldname_cpp }} {{ alias.newname }};
{% endfor %}
}}}

#endif // __KL2EDK_AUTOGEN_aliases__
