#ifndef __KL2EDK_AUTOGEN_{{ manager.ext_name }}__
#define __KL2EDK_AUTOGEN_{{ manager.ext_name }}__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including '{{ manager.ext_name }}.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version {{ version_full }}
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != {{ version_maj }} || FABRIC_EDK_VERSION_MIN != {{ version_min }}
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

{% for type_name in manager.types %}
#include "{{ type_name }}.h"
{% if manager.is_object(type_name) or manager.is_interface(type_name) %}
#include "{{ type_name }}_impl.h"
{% endif %}
{% endfor %}
{% for header in function_headers %}
#include "{{ header }}_functions.h"
{% endfor %}

#endif // __KL2EDK_AUTOGEN_{{ manager.ext_name }}__
