#ifndef __KL2EDK_AUTOGEN_global_functions__
#define __KL2EDK_AUTOGEN_global_functions__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'global_functions.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version {{ version_full }}
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != {{ version_maj }} || FABRIC_EDK_VERSION_MIN != {{ version_min }}
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

{% for function in manager.functions %}
{% if function.symbol %}
// Defined at {{ function.location }}
FABRIC_EXT_EXPORT
{% if manager.uses_returnval(function.ret_type_name) %}
  {{ function.ret_type_name_cpp_full }}
{% else %}
  void
{% endif %}
  {{ function.symbol }}(
{% if function.ret_type_name and not manager.uses_returnval(function.ret_type_name) %}
    Fabric::EDK::KL::Traits< {{ function.ret_type_name_cpp_full }} >::Result _result
{% endif %}
{% for param in function.params %}
{% if (function.ret_type_name and not manager.uses_returnval(function.ret_type_name)) or not loop.first %}
,
{% endif %}
    Fabric::EDK::KL::Traits< {{ param.type_name_cpp_full }} >::{{ param.usage_cpp }} {{ param.name -}}
{% endfor %}

);

{% endif %}
{% endfor %}

#endif // __KL2EDK_AUTOGEN_global_functions__
